version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - bookstore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bookstore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vladp
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vladp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bookstore-network

volumes:
  postgres_data:
  redis_data:

networks:
  bookstore-network:
    driver: bridge